### ISSUE TITLE
RABBITMQ_VM_MEMORY_HIGH_WATERMARK value rejected from example template.

### ISSUE THREAD

**Issue by jghankins** [malawson/rabbitmq-ecs-autoclustering#1]
Starting to work on getting this stood up.  I'm getting an invalid parameter for 0.85 and it defaults back to .4. Presuming this should not have a preceding value before the decimal.

**Comment by malawson** [comment]
@jghankins it should now be fixed https://github.com/malawson/rabbitmq-ecs-autoclustering/commit/6418aeaa8f23a4c13b5b9a07e58b3ee1dfbaead8
the thing is the docker-entrypoint.sh applies the RABBITMQ_VM_MEMORY_HIGH_WATERMARK environment variable in the rabbit config at /etc/rabbitmq/rabbitmq.config. Rebuild your docker image and you should be fine.
